# Header
menu:
  Home: /
  Archives: /archives
  About: /about
rss:
github: https://github.com/jiahuixyz
logo_title: Hexo
blog_title: 念牧童的博客

# Content
excerpt_link: Read More
fancybox: true
mathjax: false

# Sidebar
sidebar: right
widgets:
  - recent_posts
  - tag
  - archive

# Miscellaneous
wx_block: false
google_analytics:
favicon:
twitter:
google_plus:
fb_admins:
fb_app_id:

# Duoshuo
duoshuo_shortname:

# Swiftype Search
swiftype_key:
